### ISSUE TITLE
Internal Server Error when clicked on Remove Saved Items button

### ISSUE THREAD

**Issue by geekinsta** [geekinsta/Learn.Geekinsta#9]
Clicking remove saved button under the favorite section of student dashboard triggers 500x Internal Server Error.

**Comment by mishelshaji** [comment]
This occurred due to a URL routing mismatch. We changed the course detail page URL to **/course/course-URL** in the last update. And **/course/clear-favorite/** is routed to the course detail page causing the error. I will change the course details page URL in the next update.
